const battleFormations = [
  {
    id: "orruk-warclans",
    type: "Battle Formation",
    faction: "orruks",
    subfaction: "Orruk Warclans",
    name: "Orruk Warclans",
    description: "Ejército principal de Orruk Warclans.",
    season: "2026-27",
    source: "Battletome: Orruk Warclans",
    active: true,
  },
  {
    id: "big-waaagh",
    type: "Army of Renown",
    faction: "orruks",
    subfaction: "Big Waaagh!",
    name: "Big Waaagh!",
    description: "Ejército de Renombre.",
    season: "2026-27",
    source: "Battletome: Orruk Warclans",
    active: true,
  },
  {
    id: "bonesplitterz",
    type: "Legends",
    faction: "orruks",
    subfaction: "Bonesplitterz",
    name: "Bonesplitterz",
    description: "Ejército Legends.",
    season: "2026-27",
    source: "Battletome: Orruk Warclans",
    active: true,
  },
  {
    id: "ironjawz",
    type: "Battle Formation",
    faction: "orruks",
    subfaction: "Ironjawz",
    name: "Ironjawz",
    description: "Ejército principal Ironjawz.",
    season: "2026-27",
    source: "Battletome: Orruk Warclans",
    active: true,
  },
  {
    id: "krazoggs-grunta-stampede",
    type: "Army of Renown",
    faction: "orruks",
    subfaction: "Krazogg's Grunta Stampede",
    name: "Krazogg's Grunta Stampede",
    description: "Ejército de Renombre.",
    season: "2026-27",
    source: "Battletome: Orruk Warclans",
    active: true,
  },
  {
    id: "kruleboyz",
    type: "Battle Formation",
    faction: "orruks",
    subfaction: "Kruleboyz",
    name: "Kruleboyz",
    description: "Ejército principal Kruleboyz.",
    season: "2026-27",
    source: "Battletome: Orruk Warclans",
    active: true,
  },
  {
    id: "murkvast-menagerie",
    type: "Army of Renown",
    faction: "orruks",
    subfaction: "Murkvast Menagerie",
    name: "Murkvast Menagerie",
    description: "Ejército de Renombre.",
    season: "2026-27",
    source: "Battletome: Orruk Warclans",
    active: true,
  },
  {
    id: "zoggroks-ironmongerz",
    type: "Army of Renown",
    faction: "orruks",
    subfaction: "Zoggrok's Ironmongerz",
    name: "Zoggrok's Ironmongerz",
    description: "Ejército de Renombre.",
    season: "2026-27",
    source: "Battletome: Orruk Warclans",
    active: true,
  },
];

export default battleFormations;